{
  lib,
  ...
}:
{
  # =========================================================================
  #      Hardware Configuration
  # =========================================================================

  # Add hardware-specific configuration here
  # This file should be generated by running `nixos-generate-config` on the target system
  # or manually configuring as required.

  boot = {
    supportedFilesystems = [
      "btrfs"
      "vfat"
      "f2fs"
      "xfs"
      "ntfs"
      "cifs"
      "nfs"
    ];

    initrd = {
      availableKernelModules = [
        "ahci"
        "nvme"
        "phy_rockchip_naneng_combphy"
        "sd_mod"
        "uas"
        "usb_storage"
        "usbhid"
        "xhci_pci"
      ];

      kernelModules =
        [
        ];
    };

    kernelModules =
      [
      ];

    kernelParams = [
      "mitigations=off"
      "threadirqs"
      "console=ttyS0"
    ];

    extraModulePackages = [ ];
  };

  fileSystems = {

    "/" = lib.mkDefault {
      device = "/dev/disk/by-label/nixos";
      fsType = "ext4";
      options = [ "defaults" ];
    };

    "/boot" = lib.mkDefault {
      device = "/dev/disk/by-label/ESP";
      fsType = "vfat";
      options = [ "defaults" ];
      neededForBoot = true;
    };

  };

  swapDevices = [ ];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";

  hardware = {
    enableAllFirmware = true;
    enableRedistributableFirmware = true;
  };

}
